version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wastedb
      SPRING_DATASOURCE_USERNAME: tisztatisza
      SPRING_DATASOURCE_PASSWORD: tisztatisza
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: tisztatisza
      POSTGRES_PASSWORD: tisztatisza
      POSTGRES_DB: wastedb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend