name: React App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest
    env:
      EXAMPLE: example # environment variable

    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      # cache the dependencies to speed up the build
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # install dependencies
      - name: Install dependencies
        run: bun i
        working-directory: frontend

      # build the react app
      - name: Build
        run: bun run build
        working-directory: frontend

      # deploy the react app to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # NOTE: GITHUB_TOKEN is a secret token that is automatically generated by GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist # directory to deploy    